# Generated by Django 5.2 on 2025-05-18 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CropEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('seeding', 'Seeding'), ('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('harvesting', 'Harvesting')], max_length=20)),
                ('event_date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.crop')),
            ],
        ),
    ]
