# Generated by Django 5.2 on 2025-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="रकम (रु.)"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("crop_sales", "बाली बिक्री"),
                    ("equipment_purchase", "उपकरण खरिद"),
                    ("fertilizer", "मल/बिउ खरिद"),
                    ("transport", "यातायात"),
                    ("labor", "श्रमिक खर्च"),
                    ("loan_payment", "ऋण भुक्तानी"),
                    ("misc", "अन्य"),
                ],
                max_length=50,
                verbose_name="श्रेणी",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="मिति"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="विवरण"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "आय"), ("expense", "खर्च")],
                max_length=7,
                verbose_name="प्रकार",
            ),
        ),
    ]
