# Generated by Django 5.2 on 2025-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_reply_likes_alter_post_banner_delete_replylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('crops', 'Crops'), ('fertilizers', 'Fertilizers'), ('market', 'Market')], default='crops', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
