# Generated by Django 5.2 on 2025-05-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_category_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('crops', 'बाली'), ('fertilizers', 'मलहरू '), ('market', 'बजार'), ('other', 'अन्य')], default='other', max_length=20),
        ),
    ]
